Traceback (most recent call last):
  File "tomography/XRD1611.py", line 65, in <module>
    perform_function_call(sock, set_camera_mode, handle, 0)  # the base time will be timing 0
  File "C:\Users\ToratomControl\Projects\Zajex\tomography\flat_panel\common.py", line 18, in perform_function_call
    send_message(sock, getattr(FunctionCode, function.__name__), ret, name)
  File "C:\Users\ToratomControl\Projects\Zajex\tomography\Socket.py", line 127, in send_message
    sock.sendall(msg)
  File "C:\Users\ToratomControl\miniconda3\envs\py27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

ERROR conda.cli.main_run:execute(125): `conda run python tomography/XRD1611.py` failed. (See above for error)
C:\Users\ToratomControl\Projects\Zajex\tomography\flat_panel\XISL.dll
C:\Users\ToratomControl\Projects\Zajex\tomography\flat_panel\XISL.dll
Connecting to server at localhost:8080
Initializing detector...
Function enum_sensors() executed successfully.
Detected (1L,) sensors. Using only the first one...
Function get_next_sensor() executed successfully.
Function get_configuration(c_void_p(2L),) executed successfully.
Creating empty array for data...
Function set_callbacks_and_messages(c_void_p(2L), <CFunctionType object at 0x00000000048C4118>, <CFunctionType object at 0x00000000048C41E8>) executed successfully.
Function define_dest_buffers(c_void_p(2L), <__main__.c_ushort_Array_4096_Array_4096_Array_1 object at 0x00000000048B7F48>, 1, 4096L, 4096L) executed successfully.
Function set_camera_binning_mode(c_void_p(2L), 257) executed successfully.
Function set_camera_trigger_mode(c_void_p(2L), 3) executed successfully.
Function set_camera_gain(c_void_p(2L), 0) executed successfully.
Function set_camera_mode(c_void_p(2L), 0) executed successfully.
DLLMain()-DLL_PROCESS_ATTACH
Init Mutex created
Read Mutex created
Close Init Mutex
Close Read Mutex

